"""add landmark location_gated_tools

Revision ID: b34a1e4233ff
Revises: b675fd375f81
Create Date: 2026-06-17 14:38:16.498331
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b34a1e4233ff'
down_revision: Union[str, None] = 'b675fd375f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landmarks', sa.Column('location_gated_tools', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landmarks', 'location_gated_tools')
    # ### end Alembic commands ###
