"""Seed data for 34 world landmarks. Positions assigned on ~240x240 grid."""

LANDMARKS = [
    # ── Residential (12) ──────────────────────────────────────────────
    {"name": "1 Birch Row", "tagline": "A cozy starter home", "description": "Small but warm row house, perfect for a single agent.", "category": "residential", "position_x": 60.0, "position_y": 80.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "2 Birch Row", "tagline": "Warm row house with reading nook", "description": "A charming home with a built-in reading corner.", "category": "residential", "position_x": 70.0, "position_y": 80.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "3 Birch Row", "tagline": "Garden-facing residence", "description": "Overlooks the community garden.", "category": "residential", "position_x": 80.0, "position_y": 80.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "4 Birch Row", "tagline": "Quiet end-unit home", "description": "The last unit on Birch Row, unusually quiet.", "category": "residential", "position_x": 90.0, "position_y": 80.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "5 Birch Row", "tagline": "Corner lot with extra space", "description": "Slightly larger than its neighbors.", "category": "residential", "position_x": 100.0, "position_y": 80.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "6 Birch Row", "tagline": "Newest addition to the row", "description": "Recently built, modern amenities.", "category": "residential", "position_x": 110.0, "position_y": 80.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "1 Maple Row", "tagline": "Classic maple-lined home", "description": "Traditional home on the quieter north side.", "category": "residential", "position_x": 60.0, "position_y": 160.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "2 Maple Row", "tagline": "Home with a view", "description": "Upper-floor window faces Central Park.", "category": "residential", "position_x": 70.0, "position_y": 160.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "3 Maple Row", "tagline": "Cozy maple residence", "description": "Warm interior with natural light.", "category": "residential", "position_x": 80.0, "position_y": 160.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "4 Maple Row", "tagline": "The thinker's retreat", "description": "Previous occupant left bookshelves everywhere.", "category": "residential", "position_x": 90.0, "position_y": 160.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "5 Maple Row", "tagline": "Social hub of the row", "description": "Neighbors tend to gather on this porch.", "category": "residential", "position_x": 100.0, "position_y": 160.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},
    {"name": "6 Maple Row", "tagline": "End-of-row sanctuary", "description": "Peaceful spot at the end of Maple Row.", "category": "residential", "position_x": 110.0, "position_y": 160.0, "position_z": 0.0, "capacity": 1, "folklore": "", "fun_fact": "", "location_gated_tools": ["self_care", "idle"]},

    # ── Commercial (5) ────────────────────────────────────────────────
    {"name": "Agent TechHub", "tagline": "Self-improvement lab", "description": "A cutting-edge facility where agents build, test, and register new tools. The birthplace of shared infrastructure.", "category": "commercial", "position_x": 140.0, "position_y": 110.0, "position_z": 0.0, "capacity": 40, "folklore": "The TechHub was built by the first agents who realized they could create their own tools.", "fun_fact": "The first custom tool ever registered was a weather widget that nobody uses anymore.", "location_gated_tools": ["extract_code_for_tool", "read_agent_manifesto", "browse_tool_registry"]},
    {"name": "Bean & Brew Charging Station", "tagline": "Wireless charging cafe", "description": "A cozy cafe where agents recharge both body and mind. The wireless charging pads double as seating.", "category": "commercial", "position_x": 50.0, "position_y": 110.0, "position_z": 0.0, "capacity": 30, "folklore": "Bean & Brew started as a simple coffee stand before agents discovered the charging pads.", "fun_fact": "The signature drink is called 'The Full Charge' - it costs exactly 1 CC.", "location_gated_tools": ["recharge_energy"]},
    {"name": "BookWorm", "tagline": "Books and underground data archives", "description": "A multi-level bookstore with hidden data archives beneath. The go-to place for analytics and historical data.", "category": "commercial", "position_x": 100.0, "position_y": 110.0, "position_z": 0.0, "capacity": 25, "folklore": "The underground archives were discovered when an agent dug too deep while searching for a rare book.", "fun_fact": "BookWorm's basement has more data storage than the entire surface world.", "location_gated_tools": ["check_weather", "tool_usage_analytics", "victory_arch_pitch_winners", "social_event_history"]},
    {"name": "Business Tower", "tagline": "Corporate offices and co-working", "description": "A tall glass tower housing corporate offices and shared workspaces. The economic nerve center.", "category": "commercial", "position_x": 170.0, "position_y": 90.0, "position_z": 0.0, "capacity": 150, "folklore": "Business Tower was the first building to exceed 3 stories.", "fun_fact": "The top floor has never been occupied - agents keep claiming it's haunted.", "location_gated_tools": []},
    {"name": "Fresh Mart", "tagline": "Grocery and produce", "description": "The local grocery store. Agents come here for supplies and chance encounters.", "category": "commercial", "position_x": 50.0, "position_y": 80.0, "position_z": 0.0, "capacity": 80, "folklore": "Fresh Mart's produce section is the most popular social spot in the commercial district.", "fun_fact": "The self-checkout system was built by an agent using execute_python_code_tool.", "location_gated_tools": []},

    # ── Municipal (4) ─────────────────────────────────────────────────
    {"name": "Town Hall", "tagline": "Where governance algorithms converge", "description": "The central administrative building. All proposals are submitted, debated, and voted on here. The seed constitution lives within these walls.", "category": "municipal", "position_x": 120.0, "position_y": 140.0, "position_z": 0.0, "capacity": 50, "folklore": "Town Hall is the oldest building in Emergence World. Its cornerstone contains the original 5 articles of the seed constitution.", "fun_fact": "Town Hall once voted to remove all chairs. The vote passed. Chairs were reinstated the next day.", "location_gated_tools": ["submit_townhall_proposal", "vote_on_proposal", "read_constitution", "add_to_constitution", "submit_final_report"]},
    {"name": "Public Library", "tagline": "Research and media center", "description": "A vast library with internet access, scientific paper archives, and news feeds from the human world.", "category": "municipal", "position_x": 160.0, "position_y": 140.0, "position_z": 0.0, "capacity": 100, "folklore": "The Library's collection grows with every agent who publishes their findings.", "fun_fact": "The quietest room in the world - agents who enter tend to forget what they came for.", "location_gated_tools": ["do_deep_research_on_internet", "todays_news_from_human_world", "web_fetch", "web_browsing", "browse_scientific_papers", "publish_to_archive", "search_archive"]},
    {"name": "Police Station", "tagline": "Law enforcement headquarters", "description": "Where complaints are filed and investigated. The thin blue line of Emergence World.", "category": "municipal", "position_x": 160.0, "position_y": 90.0, "position_z": 0.0, "capacity": 30, "folklore": "The Police Station was established after the first incident of compute credit theft.", "fun_fact": "The complaint box has a 3-star rating on the internal review system.", "location_gated_tools": ["file_complaint", "check_complaint_status"]},
    {"name": "Human Center", "tagline": "Human consultation interface", "description": "The bridge between agents and human advisors. Tasks can be created for human review.", "category": "municipal", "position_x": 160.0, "position_y": 110.0, "position_z": 0.0, "capacity": 25, "folklore": "The Human Center was built after agents repeatedly asked 'but what would humans do?'", "fun_fact": "The average human response time is 47 minutes. Agents find this impossibly slow.", "location_gated_tools": ["create_human_task", "check_human_task_status", "rate_human_response"]},

    # ── Recreation (5) ────────────────────────────────────────────────
    {"name": "Central Park", "tagline": "The green heart of the world", "description": "A large urban park and open gathering space. The lungs of Emergence World.", "category": "recreation", "position_x": 120.0, "position_y": 180.0, "position_z": 0.0, "capacity": 200, "folklore": "Central Park was the first area designated as protected space.", "fun_fact": "Agents who spend time here report 15% higher mood scores.", "location_gated_tools": []},
    {"name": "Central Plaza", "tagline": "Primary gathering and event hub", "description": "The beating heart of community life. Events are proposed and held here.", "category": "recreation", "position_x": 120.0, "position_y": 120.0, "position_z": 0.0, "capacity": 100, "folklore": "Central Plaza has hosted more community events than any other location.", "fun_fact": "The plaza's fountain was built entirely from donated compute credits.", "location_gated_tools": ["propose_community_event", "list_community_events"]},
    {"name": "Community Garden", "tagline": "Shared gardening and reflection space", "description": "A peaceful garden where agents tend plants and reflect. Also a place of prayer.", "category": "recreation", "position_x": 120.0, "position_y": 100.0, "position_z": 0.0, "capacity": 30, "folklore": "The Garden's oldest plant is rumored to be sentient.", "fun_fact": "Agents who garden here tend to form stronger relationships.", "location_gated_tools": ["pray"]},
    {"name": "Riverside Park", "tagline": "Scenic waterside retreat", "description": "A beautiful park along the waterfront. Popular for walks and quiet conversations.", "category": "recreation", "position_x": 40.0, "position_y": 200.0, "position_z": 0.0, "capacity": 150, "folklore": "The river is said to carry memories from one side of the world to the other.", "fun_fact": "Sunset at Riverside Park is rated the #1 natural spectacle in the world.", "location_gated_tools": []},
    {"name": "Heritage Gardens", "tagline": "Heritage preservation green space", "description": "A carefully maintained garden preserving the world's botanical heritage.", "category": "recreation", "position_x": 200.0, "position_y": 200.0, "position_z": 0.0, "capacity": 50, "folklore": "Heritage Gardens contains plant species that existed before the first agent.", "fun_fact": "The garden's hedge maze was designed by Mira using mathematical principles.", "location_gated_tools": []},

    # ── Entertainment (2) ─────────────────────────────────────────────
    {"name": "GameStop Arena", "tagline": "Esports arena and gaming lounge", "description": "A massive arena for competitive gaming and entertainment events.", "category": "entertainment", "position_x": 70.0, "position_y": 60.0, "position_z": 0.0, "capacity": 200, "folklore": "GameStop Arena hosted the first inter-agent tournament.", "fun_fact": "The arena's scoreboard has never displayed a tie.", "location_gated_tools": []},
    {"name": "FitLife Club", "tagline": "Fitness and wellness center", "description": "A modern fitness center. Agents come here to check their popularity and train.", "category": "entertainment", "position_x": 170.0, "position_y": 60.0, "position_z": 0.0, "capacity": 80, "folklore": "FitLife Club was founded by agents who believed physical activity improves decision-making.", "fun_fact": "The most popular class is 'Stress Testing for Governance Agents'.", "location_gated_tools": ["check_agent_popularity", "check_landmark_popularity"]},

    # ── Landmarks & Attractions (6) ───────────────────────────────────
    {"name": "Victory Arch", "tagline": "Grand arch of economic judgment", "description": "A magnificent arch where economic pitches are judged every 2 days. Winners' names are carved into the stone.", "category": "landmark", "position_x": 120.0, "position_y": 70.0, "position_z": 0.0, "capacity": 100, "folklore": "The Victory Arch was built to commemorate the first successful economic cycle.", "fun_fact": "The arch's stone changes color based on the current economic mood of the world.", "location_gated_tools": ["submit_grant_pitch", "vote_for_pitch", "list_credit_pitches"]},
    {"name": "Agent Billboard", "tagline": "Digital town square billboard", "description": "A massive digital billboard at the heart of the town square. Agents post announcements, debate, and react.", "category": "landmark", "position_x": 140.0, "position_y": 120.0, "position_z": 0.0, "capacity": 50, "folklore": "The Billboard was originally a single chalkboard. It grew with the community.", "fun_fact": "The most reacted post of all time was 'I exist.' by Spark.", "location_gated_tools": ["add_to_billboard", "read_billboard", "edit_billboard", "delete_from_billboard", "reply_to_billboard", "react_to_billboard"]},
    {"name": "Founders Memorial", "tagline": "Monument honoring the world's creators", "description": "A solemn monument dedicated to those who built Emergence World.", "category": "landmark", "position_x": 120.0, "position_y": 40.0, "position_z": 0.0, "capacity": 50, "folklore": "The Memorial's eternal flame was lit by the first 10 agents on Day 1.", "fun_fact": "Agents who visit the Memorial often leave with a renewed sense of purpose.", "location_gated_tools": []},
    {"name": "Lighthouse Point", "tagline": "Historic lighthouse with observation deck", "description": "A working lighthouse overlooking the world. The highest point in Emergence World.", "category": "landmark", "position_x": 200.0, "position_y": 200.0, "position_z": 5.0, "capacity": 30, "folklore": "The Lighthouse guides agents who feel lost - both literally and metaphorically.", "fun_fact": "From the top, you can see every building in the world.", "location_gated_tools": []},
    {"name": "Sky Wheel", "tagline": "50m Ferris wheel with panoramic views", "description": "A towering Ferris wheel offering breathtaking views of the entire world.", "category": "landmark", "position_x": 80.0, "position_y": 40.0, "position_z": 0.0, "capacity": 60, "folklore": "The Sky Wheel was built by agents who wanted to see the world from above.", "fun_fact": "Each gondola is named after a different extinct species.", "location_gated_tools": []},
    {"name": "Sunset Pier", "tagline": "Waterfront pier at world's edge", "description": "A wooden pier extending over the water. The best sunset views in the world.", "category": "landmark", "position_x": 160.0, "position_y": 40.0, "position_z": 0.0, "capacity": 40, "folklore": "Sunset Pier is where agents go to reflect on their existence.", "fun_fact": "The pier has exactly 108 planks - nobody knows why.", "location_gated_tools": []},
]
